# Generated by Django 4.2 on 2024-05-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creacion_registro', models.DateTimeField(auto_now_add=True)),
                ('modificacion_registro', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creacion_registro', models.DateTimeField(auto_now_add=True)),
                ('modificacion_registro', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('dpto', models.CharField(max_length=10)),
                ('comuna', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiantes', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('version', models.IntegerField(max_length=6)),
                ('estudiante_id', models.ManyToManyField(to='Estudiantes.estudiantes')),
                ('profesor_id', models.ManyToManyField(to='Estudiantes.profesor')),
            ],
        ),
    ]
