# Generated by Django 4.2 on 2024-05-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estudiante_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiantes'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
